#!/bin/bash

echo "======================================"
echo "GitHub Secrets Configuration"
echo "======================================"
echo ""
echo "Copy the values below and add them as secrets in your GitHub repository:"
echo "Go to: https://github.com/simoesdb-ship-it/Eve-app/settings/secrets/actions"
echo ""
echo "--------------------------------------"
echo "Secret 1: KEYSTORE_BASE64"
echo "--------------------------------------"
base64 mobile/android/app/pattern-discovery-release-key.keystore | tr -d '\n'
echo ""
echo ""
echo "--------------------------------------"
echo "Secret 2: KEYSTORE_PASSWORD"
echo "--------------------------------------"
echo "PatternDiscovery2025!"
echo ""
echo "--------------------------------------"
echo "Secret 3: KEY_ALIAS"
echo "--------------------------------------"
echo "pattern-discovery-key"
echo ""
echo "======================================"
echo "Next Steps:"
echo "======================================"
echo "1. Copy each value above"
echo "2. Go to GitHub repository settings → Secrets → Actions"
echo "3. Click 'New repository secret' for each one"
echo "4. Paste the name and value"
echo "5. Click 'Add secret'"
echo ""
echo "After adding secrets, push your code to trigger the build!"
echo "======================================"
